{% set pytest_args = "python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k \"not classifier_gt_tox\"" %}
{% set version = "2.1.3" %}
{% set pytest_args = 'python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not classifier_gt_tox"' %}

package:
  name: pyproject-fmt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-fmt/pyproject_fmt-{{ version }}.tar.gz
  sha256: 4fe12151c48504202fd8b1eae27e0d584c31e69f6e58c97dca6df504bdeb191a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyproject-fmt = pyproject_fmt.__main__:run

requirements:
  host:
    - hatch-vcs >=0.4
    - hatchling >=1.24.2
    - pip
    - python >=3.8
  run:
    - pyproject-fmt-rust ==1.1.1
    - python >=3.8
    - tomli >=2.0.1
test:
  source_files:
    - tests
  imports:
    - pyproject_fmt
  commands:
    - pip check
    - pyproject-fmt --help
    - {{ pytest_args }} --cov-fail-under=92  # [unix]
    # fails with `FileNotFoundError`
    - {{ pytest_args }} -k "not test_help_invocation_as_script"  # [win]
  requires:
    - pip
    - pytest >=8.2
    - pytest-cov >=5
    - pytest-mock >=3.14

about:
  home: https://pypi.org/project/pyproject-fmt
  summary: Format your pyproject.toml file
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://pyproject-fmt.readthedocs.io
  dev_url: https://github.com/tox-dev/pyproject-fmt
  description: |
    Apply a consistent format to your `pyproject.toml` file with comment support.

extra:
  recipe-maintainers:
    - bollwyvl
