{% set pytest_args = "python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k \"not classifier_gt_tox\"" %}
{% set pytest_args = "python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k \"not classifier_gt_tox\"" %}
{% set version = "1.3.0" %}
{% set pytest_args = 'python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not classifier_gt_tox"' %}

package:
  name: pyproject-fmt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-fmt/pyproject_fmt-{{ version }}.tar.gz
  sha256: d4d3dc401fb2c433390ad318a8467c67fc9273e772819d02940b76030b88d428

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - pyproject-fmt = pyproject_fmt.__main__:run

requirements:
  host:
    - hatch-vcs >=0.3
    - hatchling >=1.18
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - natsort >=8.4
    - packaging >=23.1
    - tomlkit >=0.12.1

test:
  source_files:
    - tests
  imports:
    - pyproject_fmt
  commands:
    - pip check
    - pyproject-fmt --help
    - {{ pytest_args }} --cov-fail-under=92  # [not win]
    # fails with `FileNotFoundError``
    - {{ pytest_args }} -k "not test_help_invocation_as_script"  # [win]
  requires:
    - pip
    - pytest >=7.4
    - pytest-cov >=4
    - pytest-mock >=3.11

about:
  home: https://pypi.org/project/pyproject-fmt
  summary: Format your pyproject.toml file
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://pyproject-fmt.readthedocs.io
  dev_url: https://github.com/tox-dev/pyproject-fmt
  description: |
    Apply a consistent format to your `pyproject.toml` file with comment support.

extra:
  recipe-maintainers:
    - bollwyvl
