{% set version = "2.4.3" %}

# the `if` avoids bot dupes
{% if 1 %}
{% set pytest_args = 'python -m pytest -vv --cov=pyproject_fmt --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not classifier_gt_tox"' %}
{% set win_skips = 'help_invocation_as_script or cli_pyproject_toml_not_file' %}
{% endif %}

package:
  name: pyproject-fmt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyproject-fmt/pyproject_fmt-{{ version }}.tar.gz
  sha256: 68c9dc7e360cd169ba323238bab8d0659cbf0ce4380bf787973c3a042829de70

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  entry_points:
    - pyproject-fmt = pyproject_fmt.__main__:run

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.7.1                        # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("rust") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - maturin >=1.7.1
    - pip
    - python
  run:
    - python

test:
  source_files:
    - pyproject-fmt/tests
  imports:
    - pyproject_fmt
  commands:
    - pip check
    - pyproject-fmt --help
    - cd pyproject-fmt
    - {{ pytest_args }} --cov-fail-under=92         # [unix]
    - {{ pytest_args }} -k "not ({{ win_skips }})"  # [win]
  requires:
    - pip
    - pytest >=8.2
    - pytest-cov >=5
    - pytest-mock >=3.14

about:
  home: https://pypi.org/project/pyproject-fmt
  summary: Format your pyproject.toml file
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/tox-dev/toml-fmt
  description: Format your pyproject.toml file

extra:
  recipe-maintainers:
    - bollwyvl
