# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.15.2"
  maturin_min: "1.11.5"
  python_check_max: "3.14"

package:
  name: pyproject-fmt
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyproject-fmt/pyproject_fmt-${{ version }}.tar.gz
  sha256: 10b22effb4c1ac12033d41b089bee60aded60f2241e0b95f2794917fc7d5dac8

build:
  number: 0
  skip: is_abi3 and not is_python_min
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  python:
    entry_points:
      - pyproject-fmt = pyproject_fmt.__main__:runner
    version_independent: ${{ is_abi3 }}

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - maturin >=${{ maturin_min }}
        - python
        - if: is_abi3
          then:
            - python-abi3
  host:
    - maturin >=${{ maturin_min }}
    - pip
    - python
    - if: is_abi3
      then:
        - python-abi3
  run:
    - python
    - toml-fmt-common ==1.2

tests:
  - if: is_abi3
    then:
      - python:
          imports: pyproject_fmt
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
    else:
      - python:
          imports: pyproject_fmt
          pip_check: true
  - files:
      recipe:
        - run_test.py
      source:
        - pyproject-fmt/tests/
    requirements:
      run:
        - pytest >=8.4.2
        - pytest-cov >=7
        - pytest-mock >=3.15.1
        - if: is_abi3
          then:
            - abi3audit
            - python ${{ python_min }}.*
    script:
      - pyproject-fmt --help
      - python run_test.py --python-min=${{ python_min }}

about:
  summary: Format your pyproject.toml file
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/pyproject-fmt
  repository: https://github.com/tox-dev/toml-fmt

extra:
  recipe-maintainers:
    - bollwyvl
