# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.5.1
  maturin_version: ">=1.7.1"

package:
  name: pyproject-fmt
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyproject-fmt/pyproject_fmt-${{ version }}.tar.gz
  sha256: c7dfe1f62cc91fdf7ec73043b12c0df03a9a828ce09067fa4bb522fea5b24269

build:
  number: 0
  # only build for the minimal python version
  skip: not (match(python, python_min ~ ".*") and is_abi3 == 'true')
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  python:
    entry_points:
      - pyproject-fmt = pyproject_fmt.__main__:runner

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin ${{ maturin_version }}
  host:
    - maturin ${{ maturin_version }}
    - pip
    - python
    - python-abi3
  run:
    - python
    - toml-fmt-common ==1.0.1

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: pyproject_fmt
  - files:
      recipe:
        - run_test.py
      source:
        - pyproject-fmt/tests/
    requirements:
      run:
        - pytest >=8.2
        - pytest-cov >=5
        - pytest-mock >=3.14
    script:
      - pyproject-fmt --help
      - python run_test.py

about:
  summary: Format your pyproject.toml file
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/pyproject-fmt
  repository: https://github.com/tox-dev/toml-fmt

extra:
  recipe-maintainers:
    - bollwyvl
